config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  devise_scope :user do
    get '/users/sign_out', to: 'devise/sessions#destroy'
  end
  
  resources :patients

  root  'doctors#patients'

  get 'doctors/patients', to: 'doctors#patients', as: 'doctors_patients'
  get 'doctors/chart', to: 'doctors#chart', as: 'doctors_chart'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/chart.rb
class Chart < ApplicationRecord
    validates :patient_count, presence: true
    validates :registration_date, presence: true
end

app/models/patient.rb
class Patient < ApplicationRecord
    belongs_to :user

    validates :name, presence: true
    validates :phone_number, presence: true, length: { is: 10 }
    validates :birth_date, presence: true
    validates :gender, presence: true
    validates :address, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :patients
  
  # in rails-c 'User.roles'
  enum role: { receptionist: 'receptionist', doctor: 'doctor' }

  validates :role, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

    def after_sign_in_path_for(resource)
        case resource.role
        when 'doctor'
          doctors_patients_path
        when 'receptionist'
          patients_path
        else
          super
        end
      end
end

app/controllers/doctors_controller.rb
class DoctorsController < ApplicationController
    before_action :authenticate_user!

    def patients
      @patients = Patient.all
    end
  
    def chart
      @patients_data = Patient.group_by_day(:created_at).count
      @labels = @patients_data.keys
      @data = @patients_data.values
    end
end

app/controllers/patients_controller.rb
class PatientsController < ApplicationController
    before_action :authenticate_user!

    def index
        @patients = current_user.patients
    end

    def new
        @patient = current_user.patients.build
    end

    def create
        @patient = current_user.patients.build(req_patient_params)
        if @patient.save
            redirect_to patients_path, notice: "Patient registered successfully."
        else  
            redirect_to patients_path, notice: "Error regestering patient, Try Again"
        end
    end

    def edit
        @patient = current_user.patients.find(params[:id])
    end

    def update
        @patient = current_user.patients.find(params[:id])
        if @patient.update(req_patient_params)
          redirect_to patients_path, notice: 'Patient details updated successfully.'
        else
          redirect_to patients_path, notice: 'Error updating patient details.'
        end
    end

    def show
        @patient = current_user.patients.find(params[:id])
        @patient.destroy
        redirect_to patients_path, notice: 'Patient data removed successfully.'
    end

    private

    def req_patient_params
        params.require(:patient).permit(:name, :phone_number, :birth_date, :gender, :address)
    end
    
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
  def sign_up_params
    params.require(:user).permit(:email, :password, :password_confirmation, :role)
  end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/doctors/chart.html.erb
<div class="container mt-5">
    <div class="row">
      <div class="col">
        <h1 class="my-4 text-center">Patient Registrations Chart</h1>
        <canvas id="patientsChart" width="800" height="400"></canvas>
      </div>
    </div>
  </div>

  <script>
    document.addEventListener('DOMContentLoaded', function() {
      var ctx = document.getElementById('patientsChart').getContext('2d');
      var myChart = new Chart(ctx, {
        type: 'line',
        data: {
          labels: <%= @labels.to_json.html_safe %>,
          datasets: [{
            label: 'Number of Patients Registered',
            data: <%= @data.to_json.html_safe %>,
            backgroundColor: 'rgba(75, 192, 192, 0.2)',
            borderColor: 'rgba(75, 192, 192, 1)',
            borderWidth: 1
          }]
        },
        options: {
          scales: {
            y: {
              beginAtZero: true
            }
          }
        }
      });
    });
  </script>

app/views/doctors/patients.html.erb
<h1 class="my-4 text-center">Patients List</h1>

<table class="table table-bordered">
  <thead class="custom-bg-light-blue">
    <tr>
      <th>Name</th>
      <th>Phone Number</th>
      <th>Date of Birth</th>
      <th>Gender</th>
      <th>Address</th>
    </tr>
  </thead>
  <tbody>
    <% @patients.each do |patient| %>
    <tr>
      <td><%= patient.name %></td>
      <td><%= patient.phone_number %></td>
      <td><%= patient.birth_date %></td>
      <td><%= patient.gender %></td>
      <td><%= patient.address %></td>
    </tr>
    <% end %>
  </tbody>
</table>

  <% flash.each do |key, value| %>
      <div class="alert alert-<%= key %>">
        <%= value %>
      </div>
  <% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Doctors Clinic</title>
    <%= csrf_meta_tags %> <%= csp_meta_tag %>
    <link
      href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css"
      rel="stylesheet"
    />
    <%= stylesheet_link_tag 'application' %>
    <script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-dark navbar-custom sticky-top">
      <div class="container-fluid">
        <a class="navbar-brand" href="/">
          <i class="fas fa-clinic-medical"></i> Doctor's Clinic
        </a>

        <div class="collapse navbar-collapse" id="navbarNav">
          <ul class="navbar-nav">
            <% if user_signed_in? %> <% if current_user.receptionist? %>
            <li class="nav-item">
              <span class="nav-link">Patient</span>
            </li>
            <% end %> <% if current_user.doctor? %>
            <li class="nav-item">
              <%= link_to 'Patients', doctors_patients_path, class: 'nav-link'
              %>
            </li>
            <li class="nav-item">
              <%= link_to 'Graph', doctors_chart_path, class: 'nav-link' %>
            </li>
            <% end %>
            <li class="nav-item">
              <%= link_to 'Logout', destroy_user_session_path, method: :delete,
              class: 'nav-link' %>
            </li>
            <% else %>
            <li class="nav-item">
              <%= link_to 'Login', new_user_session_path, class: 'nav-link' %>
            </li>
            <% end %>
          </ul>
        </div>
        
      </div>
    </nav>

    <div class="container mt-4"><%= yield %></div>

    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.5.3/dist/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
  </body>
</html>

app/views/patients/_form.html.erb
<%= form_with(model: patient, local: true, class: 'needs-validation', novalidate: true) do |form| %>
  <% if patient.errors.any? %>
    <div class="alert alert-danger">
      <h4 class="alert-heading">Oops! <%= pluralize(patient.errors.count, 'error') %> prohibited this patient from being saved:</h4>
      <ul>
        <% patient.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="mb-3">
    <%= form.label :name, class: 'form-label' %>
    <%= form.text_field :name, class: 'form-control', required: true %>
    <div class="invalid-feedback">
      Please enter a name.
    </div>
  </div>

  <div class="mb-3">
    <%= form.label :phone_number, class: 'form-label' %>
    <%= form.text_field :phone_number, class: 'form-control', required: true %>
    <div class="invalid-feedback">
      Please enter a valid phone number.
    </div>
  </div>

  <div class="mb-3">
    <%= form.label :birth_date, class: 'form-label' %>
    <%= form.date_field :birth_date, class: 'form-control', required: true %>
    <div class="invalid-feedback">
      Please enter a valid birth date.
    </div>
  </div>

  <div class="mb-3">
    <%= form.label :gender, class: 'form-label' %>
    <%= form.select :gender, ['Male', 'Female'], {}, class: 'form-select', required: true %>
    <div class="invalid-feedback">
      Please select a gender.
    </div>
  </div>

  <div class="mb-3">
    <%= form.label :address, class: 'form-label' %>
    <%= form.text_area :address, class: 'form-control', rows: 3, required: true %>
    <div class="invalid-feedback">
      Please enter an address.
    </div>
  </div>

  <div class="mb-3">
    <%= form.submit 'Save', class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/patients/edit.html.erb
<h1 class="my-4 text-center">Edit Patient Details</h1>

<%= render 'form', patient: @patient %>

app/views/patients/index.html.erb
<h1 class="my-4 text-center">Patients List</h1>

<div class="table-responsive">
  <table class="table table-hover table-bordered">
    <thead class="custom-bg-light-blue">
      <tr>
        <th>Name</th>
        <th>Phone Number</th>
        <th>Date of Birth</th>
        <th>Gender</th>
        <th>Address</th>
        <th colspan="2">Actions</th>
      </tr>
    </thead>
    <tbody>
      <% @patients.each do |patient| %>
      <tr>
        <td><%= patient.name %></td>
        <td><%= patient.phone_number %></td>
        <td><%= patient.birth_date %></td>
        <td><%= patient.gender %></td>
        <td><%= patient.address %></td>
        <td>
          <%= link_to 'Edit', edit_patient_path(patient), class: 'btn btn-outline-primary' %>
        </td>
        <td>
          <%= link_to 'Delete', patient_path(patient), method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-outline-danger' %>
        </td>
      </tr>
      <% end %>
    </tbody>
  </table>
</div>

<% flash.each do |key, value| %>
    <div class="alert alert-<%= key %> alert-dismissible fade show" role="alert">
      <%= value %>
      <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
<% end %>

<div class="text-center mt-4">
  <%= link_to 'Register New Patient', new_patient_path, class: 'btn btn-lg btn-success' %>
</div>

app/views/patients/new.html.erb
<h1 class="my-4 text-center">Register New Patient</h1>

<%= render 'form', patient: @patient %>